[package]
name = "statekit"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
description = "An immutable state-machine for validating predefined transitions."
license = "MIT"
repository = "https://github.com/whitephoenixsoft/statekit"
homepage = "https://github.com/whitephoenixsoft/statekit"
documentation = "https://docs.rs/statekit"
readme = "README.md"
keywords = ["state-machine", "fsm", "workflow", "state"]
categories = ["data-structures"]

exclude = [
	"docs/internal-docs/**",
	".gitignore"
]

[dev-dependencies]
proptest = "1.11"

[dependencies]
thiserror = "2"
